In [2]:
import numpy as np
import pandas as pd

# Python9

In [3]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [4]:
np.ones((5,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
np.full((5,5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
np.array([[1,2,3,4,5], [5,1,2,3,4], [4,5,1,2,3], [3,4,5,1,2], [2,3,4,5,1]])

array([[1, 2, 3, 4, 5],
       [5, 1, 2, 3, 4],
       [4, 5, 1, 2, 3],
       [3, 4, 5, 1, 2],
       [2, 3, 4, 5, 1]])

[[1, 1, 1],
 [0, 2, 2],
 [2, 4, 1]]

In [9]:
np.random.randint(0, 5, (3, 3))

array([[1, 3, 2],
       [0, 0, 2],
       [0, 1, 0]])

In [10]:
np.random.randint(0, 4, (3, 3))

array([[1, 3, 3],
       [0, 0, 2],
       [2, 0, 0]])

In [11]:
np.random.randint(0, 6, (3, 3))

array([[4, 0, 2],
       [3, 0, 2],
       [1, 3, 3]])

In [12]:
np.random.randint(0, 5, 3)

array([1, 0, 0])

In [13]:
np.full((4, 4), 1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [14]:
np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
np.ones((4, 4), dtype=float)


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [17]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

In [18]:
np.array(range(9))

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
np.array(range(9))


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [21]:
np.arange(1, 14, 2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [28]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
sum_last_column = big_secret[:,-1].sum()

big_secret[:5,:].diagonal().sum()

column_count = big_secret.shape[1]
big_secret[:,column_count-5:].diagonal().prod()


new_big_secret = big_secret.copy()
new_big_secret[0::2,0::2]=-1
new_big_secret[1::2, 1::2]=1

new_big_secret[:5,:].diagonal().sum()
new_big_secret[:,column_count-5:].diagonal().prod()

-1.0

# Python 9.4

In [43]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [32]:
great_secret.shape[0]

100

In [36]:
np.cos(great_secret[0,:]).sum()

0.16006721889793019

In [38]:
great_secret[great_secret > 50].sum()

5470.0

In [40]:
great_secret.flatten()[150]

7.0710678118654755

In [48]:
np.sort(great_secret, axis = 0)[-1,:].sum()

115.12148016521353

# Python 9.5

In [63]:
import bs4
html_table = '''<table>
<tbody>
<tr>
<td width="25%"><strong>ID (номер в журнале)</strong></td>
<td width="25%"><strong>Рост, см</strong></td>
<td width="25%"><strong>Масса тела, кг</strong></td>
<td width="25%"><strong>Средний балл</strong></td>
</tr>
<tr>
<td>1</td>
<td>135</td>
<td>34</td>
<td>4</td>
</tr>
<tr>
<td>2</td>
<td>160</td>
<td>43</td>
<td>5</td>
</tr>
<tr>
<td>3</td>
<td>163</td>
<td>40</td>
<td>4.3</td>
</tr>
<tr>
<td>4</td>
<td>147</td>
<td>44</td>
<td>5</td>
</tr>
<tr>
<td>5</td>
<td>138</td>
<td>41</td>
<td>4.7</td>
</tr>
<tr>
<td>6</td>
<td>149</td>
<td>54</td>
<td>3.9</td>
</tr>
<tr>
<td>7</td>
<td>136</td>
<td>39</td>
<td>4.2</td>
</tr>
<tr>
<td>8</td>
<td>154</td>
<td>48</td>
<td>4.9</td>
</tr>
<tr>
<td>9</td>
<td>137</td>
<td>35</td>
<td>3.7</td>
</tr>
<tr>
<td>10</td>
<td>165</td>
<td>60</td>
<td>4.6</td>
</tr>
</tbody>
</table>
'''

students = pd.read_html(html_table,header=0)[0] # [0] - unbox var to DataFrame
type(students)

pandas.core.frame.DataFrame

In [64]:
students.head(10)

ID (номер в журнале)  Рост, см  Масса тела, кг  Средний балл
0                     1       135              34           4.0
1                     2       160              43           5.0
2                     3       163              40           4.3
3                     4       147              44           5.0
4                     5       138              41           4.7
5                     6       149              54           3.9
6                     7       136              39           4.2
7                     8       154              48           4.9
8                     9       137              35           3.7
9                    10       165              60           4.6

In [65]:
students['Масса тела, кг'].median()

42.0

In [69]:
diff = students['Масса тела, кг'].mean() - students['Масса тела, кг'].median()
round(diff,2)

1.8

In [71]:
np.corrcoef(students['Масса тела, кг'],students['Рост, см'])

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [72]:
np.corrcoef(students['Масса тела, кг'],students['Средний балл'])

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [73]:
np.corrcoef(students['Рост, см'],students['Средний балл'])

array([[1.        , 0.46293714],
       [0.46293714, 1.        ]])

In [74]:
np.std(students['Средний балл'])

0.4517742799230607

In [75]:
np.var(students['Масса тела, кг'])

60.36

# 9.7 Python

In [101]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

In [102]:
my_slice = my_array[1:4,1:4]
my_slice

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [119]:
my_sin=np.sin(my_array)
my_sin[1:4,1:4]=1.0
x= my_sin[:,0:4].reshape((10,2))
round(np.sum(x, axis=0)[0], 3)

2.406

In [106]:
my_sin[:,:4].reshape((10,2))
my_sin[0].sum()

0.1761616497223787

In [115]:
bigdata = pd.Series(map(lambda x: x**2 ,range(101,1000,2)))
bigdata
bigdata.median()

302501.0

In [117]:
round(np.std(bigdata))

292095

In [118]:
np.corrcoef(bigdata[0::2], bigdata[1::2])

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])

# STAT&BASIC-3. Доверительные интервалы на Python
 ## 3.7 Тренировка
 

Управляющий супермаркета хочет оценить, сколько денег покупатели тратят за один поход в супермаркет в среднем. На основании ранее собранных данных известно, что расходы одного покупателя распределены приблизительно нормально. Управляющий взял случайную выборку из 15 покупателей и выяснил, что их средние расходы равны  рублей, а выборочное стандартное отклонение равно  рублей.
Давайте поможем управляющему, решив несколько задачек с помощью Python.
Подсказки для задачи
Для случая с известным значением σ предел погрешности и его интервалы
можно найти, используя функцию confidence_interval_norm():


In [21]:
from scipy.stats import norm
import math

def confidence_interval_norm(alpha, sigma, n, mean, round_degree=2):
    '''
    Для случая sigma известным
    Args:
    первый аргумент функции — уровень значимости alpha;
    второй — выборочное отклонение s или sigma ;
    третий — размер выборки n;
    четвертый — среднее значение выборки.
    '''
    value = -norm.ppf(alpha / 2) * sigma / math.sqrt(n)
    return round(mean - value,round_degree), round(mean + value,round_degree)

In [51]:
from scipy.stats import t
import math

def confidence_interval_t(alpha, sigma, n, mean,round_degree=2):
    '''
    Для случая sigma неизвестно
    alpha - степень свободы
    sigma - дисперсия
    n - размер выборки
    mean - средннее выборочное
    '''
    value = -t.ppf(alpha / 2, n - 1) * sigma / math.sqrt(n)
    return round(mean - value,round_degree),round(mean + value,round_degree)

In [17]:
print("90% - ", confidence_interval_t(alpha=0.1, sigma=400, n=15, mean=2000))
print("95% - ", confidence_interval_t(alpha=0.05, sigma=400, n=15, mean=2000))
print("99% - ", confidence_interval_t(alpha=0.01, sigma=400, n=15, mean=2000))

90% -  (1818.0, 2182.0)
95% -  (1778.0, 2222.0)
99% -  (1693.0, 2307.0)


In [19]:
print("99% - ", confidence_interval_norm(alpha=0.01, sigma=1150, n=250, mean=3540))

99% -  (3353.0, 3727.0)


In [33]:
print("95% - ", confidence_interval_t(alpha=0.05, sigma=0.81786, n=10, mean=1.19))

95% -  (0.6, 1.78)


In [26]:
import numpy as np

In [39]:

x = np.array([1.2, 0.2, 1.6, 1.9, -0.4, 0.5, 1.4, 1.7, 2.5, 1.3])
var = np.std(x)
mean = np.mean(x)
print("95% - ", confidence_interval_t(alpha=0.05, sigma=var, n=10, mean=mean, round_degree=3))

95% -  (0.605, 1.775)


# Находим z-критическое и t-критическое

In [46]:
from scipy.stats import norm 
from scipy.stats import t

Самый простой способ — найти и получить ответ как = -norm.ppf(α/2).

Например, если уровень доверия  равен 97 %, значит . Тогда мы найдем  как = -norm.ppf(0.015), то есть 2.17.

In [53]:
alpha = 0.05
value = -norm.ppf(alpha/2)
print(value) # 2.17

1.9599639845400545


In [55]:

alpha = 0.05
n = 100
value = -t.ppf(alpha/2, n - 1)
print(value)

1.9842169515086832
